### PR TITLE
Added str => sha256 && the whole beginning stuff

### PR DESCRIPTION
**Pull request by Bobbbay**
Good start! Basis is set up! The whole system is ready, all you need is a couple more tools.

Happy hacking, Bobbbay

### CODE REVIEW

**Comment by iinc0gnit0** [comment]
Please make sure you are adding on to the BlackKit.py instead of making new one.

**Comment by Bobbbay** [comment]
😅 I made a fork to work on just before you committed w/ crackedKeys...

**Comment by iinc0gnit0** [comment]
I'm sorry about that, could you add yours to it now?

**Comment by Bobbbay** [comment]
It's alright, you pretty much covered it, hehe 😏😼

**Pull request merged**
